### ISSUE TITLE
Stay consistent with CSS code formatting.

### ISSUE THREAD

**Issue by josephtkim** [schmidew/prj-rev-bwfs-dasmoto#6]
It's always best to stay consistent with your code formatting, because it makes the code follow a certain pattern, and makes the code cleaner and easier to read. For CSS, it's best to place each property on a separate line, and indenting each line by 2 spaces. For instance,

```css
.section {
  font-size: 32px;
  font-family: Helvetica;
  color: white;
  font-weight: bold;
}
```
